// source: props.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

goog.exportSymbol('proto.habitTracker.Empty', null, global);
goog.exportSymbol('proto.habitTracker.HProps', null, global);
goog.exportSymbol('proto.habitTracker.SProps', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.habitTracker.Empty = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.habitTracker.Empty, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.habitTracker.Empty.displayName = 'proto.habitTracker.Empty';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.habitTracker.HProps = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.habitTracker.HProps, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.habitTracker.HProps.displayName = 'proto.habitTracker.HProps';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.habitTracker.SProps = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.habitTracker.SProps, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.habitTracker.SProps.displayName = 'proto.habitTracker.SProps';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.habitTracker.Empty.prototype.toObject = function(opt_includeInstance) {
  return proto.habitTracker.Empty.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.habitTracker.Empty} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.habitTracker.Empty.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.habitTracker.Empty}
 */
proto.habitTracker.Empty.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.habitTracker.Empty;
  return proto.habitTracker.Empty.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.habitTracker.Empty} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.habitTracker.Empty}
 */
proto.habitTracker.Empty.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.habitTracker.Empty.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.habitTracker.Empty.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.habitTracker.Empty} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.habitTracker.Empty.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.habitTracker.HProps.prototype.toObject = function(opt_includeInstance) {
  return proto.habitTracker.HProps.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.habitTracker.HProps} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.habitTracker.HProps.toObject = function(includeInstance, msg) {
  var f, obj = {
    date: jspb.Message.getFieldWithDefault(msg, 1, ""),
    bedby12: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    cooking: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    meditation: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    training: jspb.Message.getBooleanFieldWithDefault(msg, 5, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.habitTracker.HProps}
 */
proto.habitTracker.HProps.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.habitTracker.HProps;
  return proto.habitTracker.HProps.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.habitTracker.HProps} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.habitTracker.HProps}
 */
proto.habitTracker.HProps.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDate(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setBedby12(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setCooking(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setMeditation(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTraining(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.habitTracker.HProps.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.habitTracker.HProps.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.habitTracker.HProps} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.habitTracker.HProps.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDate();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getBedby12();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getCooking();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getMeditation();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getTraining();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
};


/**
 * optional string date = 1;
 * @return {string}
 */
proto.habitTracker.HProps.prototype.getDate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.habitTracker.HProps} returns this
 */
proto.habitTracker.HProps.prototype.setDate = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bool bedBy12 = 2;
 * @return {boolean}
 */
proto.habitTracker.HProps.prototype.getBedby12 = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.habitTracker.HProps} returns this
 */
proto.habitTracker.HProps.prototype.setBedby12 = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool cooking = 3;
 * @return {boolean}
 */
proto.habitTracker.HProps.prototype.getCooking = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.habitTracker.HProps} returns this
 */
proto.habitTracker.HProps.prototype.setCooking = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bool meditation = 4;
 * @return {boolean}
 */
proto.habitTracker.HProps.prototype.getMeditation = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.habitTracker.HProps} returns this
 */
proto.habitTracker.HProps.prototype.setMeditation = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional bool training = 5;
 * @return {boolean}
 */
proto.habitTracker.HProps.prototype.getTraining = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.habitTracker.HProps} returns this
 */
proto.habitTracker.HProps.prototype.setTraining = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.habitTracker.SProps.prototype.toObject = function(opt_includeInstance) {
  return proto.habitTracker.SProps.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.habitTracker.SProps} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.habitTracker.SProps.toObject = function(includeInstance, msg) {
  var f, obj = {
    date: jspb.Message.getFieldWithDefault(msg, 1, ""),
    bedby12: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    cooking: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    meditation: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    ringfit: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    techblog: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    wakeupby8: jspb.Message.getBooleanFieldWithDefault(msg, 7, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.habitTracker.SProps}
 */
proto.habitTracker.SProps.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.habitTracker.SProps;
  return proto.habitTracker.SProps.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.habitTracker.SProps} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.habitTracker.SProps}
 */
proto.habitTracker.SProps.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDate(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setBedby12(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setCooking(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setMeditation(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRingfit(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTechblog(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setWakeupby8(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.habitTracker.SProps.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.habitTracker.SProps.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.habitTracker.SProps} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.habitTracker.SProps.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDate();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getBedby12();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getCooking();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getMeditation();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getRingfit();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getTechblog();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getWakeupby8();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
};


/**
 * optional string date = 1;
 * @return {string}
 */
proto.habitTracker.SProps.prototype.getDate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.habitTracker.SProps} returns this
 */
proto.habitTracker.SProps.prototype.setDate = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bool bedBy12 = 2;
 * @return {boolean}
 */
proto.habitTracker.SProps.prototype.getBedby12 = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.habitTracker.SProps} returns this
 */
proto.habitTracker.SProps.prototype.setBedby12 = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool cooking = 3;
 * @return {boolean}
 */
proto.habitTracker.SProps.prototype.getCooking = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.habitTracker.SProps} returns this
 */
proto.habitTracker.SProps.prototype.setCooking = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bool meditation = 4;
 * @return {boolean}
 */
proto.habitTracker.SProps.prototype.getMeditation = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.habitTracker.SProps} returns this
 */
proto.habitTracker.SProps.prototype.setMeditation = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional bool ringfit = 5;
 * @return {boolean}
 */
proto.habitTracker.SProps.prototype.getRingfit = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.habitTracker.SProps} returns this
 */
proto.habitTracker.SProps.prototype.setRingfit = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional bool techBlog = 6;
 * @return {boolean}
 */
proto.habitTracker.SProps.prototype.getTechblog = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.habitTracker.SProps} returns this
 */
proto.habitTracker.SProps.prototype.setTechblog = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional bool wakeUpBy8 = 7;
 * @return {boolean}
 */
proto.habitTracker.SProps.prototype.getWakeupby8 = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.habitTracker.SProps} returns this
 */
proto.habitTracker.SProps.prototype.setWakeupby8 = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


goog.object.extend(exports, proto.habitTracker);
