// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: props.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_props_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_props_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_props_proto_rawDescGZIP(), []int{0}
}

type HProps struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date       string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	BedBy12    bool   `protobuf:"varint,2,opt,name=bedBy12,proto3" json:"bedBy12,omitempty"`
	Cooking    bool   `protobuf:"varint,3,opt,name=cooking,proto3" json:"cooking,omitempty"`
	Meditation bool   `protobuf:"varint,4,opt,name=meditation,proto3" json:"meditation,omitempty"`
	Training   bool   `protobuf:"varint,5,opt,name=training,proto3" json:"training,omitempty"`
}

func (x *HProps) Reset() {
	*x = HProps{}
	if protoimpl.UnsafeEnabled {
		mi := &file_props_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HProps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HProps) ProtoMessage() {}

func (x *HProps) ProtoReflect() protoreflect.Message {
	mi := &file_props_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HProps.ProtoReflect.Descriptor instead.
func (*HProps) Descriptor() ([]byte, []int) {
	return file_props_proto_rawDescGZIP(), []int{1}
}

func (x *HProps) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *HProps) GetBedBy12() bool {
	if x != nil {
		return x.BedBy12
	}
	return false
}

func (x *HProps) GetCooking() bool {
	if x != nil {
		return x.Cooking
	}
	return false
}

func (x *HProps) GetMeditation() bool {
	if x != nil {
		return x.Meditation
	}
	return false
}

func (x *HProps) GetTraining() bool {
	if x != nil {
		return x.Training
	}
	return false
}

type SProps struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date       string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	BedBy12    bool   `protobuf:"varint,2,opt,name=bedBy12,proto3" json:"bedBy12,omitempty"`
	Cooking    bool   `protobuf:"varint,3,opt,name=cooking,proto3" json:"cooking,omitempty"`
	Meditation bool   `protobuf:"varint,4,opt,name=meditation,proto3" json:"meditation,omitempty"`
	Ringfit    bool   `protobuf:"varint,5,opt,name=ringfit,proto3" json:"ringfit,omitempty"`
	TechBlog   bool   `protobuf:"varint,6,opt,name=techBlog,proto3" json:"techBlog,omitempty"`
	WakeUpBy8  bool   `protobuf:"varint,7,opt,name=wakeUpBy8,proto3" json:"wakeUpBy8,omitempty"`
}

func (x *SProps) Reset() {
	*x = SProps{}
	if protoimpl.UnsafeEnabled {
		mi := &file_props_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SProps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SProps) ProtoMessage() {}

func (x *SProps) ProtoReflect() protoreflect.Message {
	mi := &file_props_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SProps.ProtoReflect.Descriptor instead.
func (*SProps) Descriptor() ([]byte, []int) {
	return file_props_proto_rawDescGZIP(), []int{2}
}

func (x *SProps) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *SProps) GetBedBy12() bool {
	if x != nil {
		return x.BedBy12
	}
	return false
}

func (x *SProps) GetCooking() bool {
	if x != nil {
		return x.Cooking
	}
	return false
}

func (x *SProps) GetMeditation() bool {
	if x != nil {
		return x.Meditation
	}
	return false
}

func (x *SProps) GetRingfit() bool {
	if x != nil {
		return x.Ringfit
	}
	return false
}

func (x *SProps) GetTechBlog() bool {
	if x != nil {
		return x.TechBlog
	}
	return false
}

func (x *SProps) GetWakeUpBy8() bool {
	if x != nil {
		return x.WakeUpBy8
	}
	return false
}

var File_props_proto protoreflect.FileDescriptor

var file_props_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x70, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x68,
	0x61, 0x62, 0x69, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x22, 0x07, 0x0a, 0x05, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x8c, 0x01, 0x0a, 0x06, 0x48, 0x50, 0x72, 0x6f, 0x70, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x65, 0x64, 0x42, 0x79, 0x31, 0x32, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x62, 0x65, 0x64, 0x42, 0x79, 0x31, 0x32, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x65, 0x64, 0x69, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x6d, 0x65, 0x64,
	0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x69, 0x6e,
	0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x74, 0x72, 0x61, 0x69, 0x6e,
	0x69, 0x6e, 0x67, 0x22, 0xc4, 0x01, 0x0a, 0x06, 0x53, 0x50, 0x72, 0x6f, 0x70, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x65, 0x64, 0x42, 0x79, 0x31, 0x32, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x62, 0x65, 0x64, 0x42, 0x79, 0x31, 0x32, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63,
	0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x65, 0x64, 0x69, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x6d, 0x65, 0x64, 0x69,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x69, 0x6e, 0x67, 0x66, 0x69,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x69, 0x6e, 0x67, 0x66, 0x69, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x74, 0x65, 0x63, 0x68, 0x42, 0x6c, 0x6f, 0x67, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x74, 0x65, 0x63, 0x68, 0x42, 0x6c, 0x6f, 0x67, 0x12, 0x1c, 0x0a, 0x09,
	0x77, 0x61, 0x6b, 0x65, 0x55, 0x70, 0x42, 0x79, 0x38, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x77, 0x61, 0x6b, 0x65, 0x55, 0x70, 0x42, 0x79, 0x38, 0x32, 0x88, 0x01, 0x0a, 0x0c, 0x48,
	0x61, 0x62, 0x69, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x12, 0x3b, 0x0a, 0x0e, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x48, 0x50, 0x72, 0x6f, 0x70, 0x73, 0x12, 0x14, 0x2e,
	0x68, 0x61, 0x62, 0x69, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x48, 0x50, 0x72,
	0x6f, 0x70, 0x73, 0x1a, 0x13, 0x2e, 0x68, 0x61, 0x62, 0x69, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b,
	0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3b, 0x0a, 0x0e, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x53, 0x50, 0x72, 0x6f, 0x70, 0x73, 0x12, 0x14, 0x2e, 0x68, 0x61, 0x62,
	0x69, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x53, 0x50, 0x72, 0x6f, 0x70, 0x73,
	0x1a, 0x13, 0x2e, 0x68, 0x61, 0x62, 0x69, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_props_proto_rawDescOnce sync.Once
	file_props_proto_rawDescData = file_props_proto_rawDesc
)

func file_props_proto_rawDescGZIP() []byte {
	file_props_proto_rawDescOnce.Do(func() {
		file_props_proto_rawDescData = protoimpl.X.CompressGZIP(file_props_proto_rawDescData)
	})
	return file_props_proto_rawDescData
}

var file_props_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_props_proto_goTypes = []interface{}{
	(*Empty)(nil),  // 0: habitTracker.Empty
	(*HProps)(nil), // 1: habitTracker.HProps
	(*SProps)(nil), // 2: habitTracker.SProps
}
var file_props_proto_depIdxs = []int32{
	1, // 0: habitTracker.HabitTracker.RegisterHProps:input_type -> habitTracker.HProps
	2, // 1: habitTracker.HabitTracker.RegisterSProps:input_type -> habitTracker.SProps
	0, // 2: habitTracker.HabitTracker.RegisterHProps:output_type -> habitTracker.Empty
	0, // 3: habitTracker.HabitTracker.RegisterSProps:output_type -> habitTracker.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_props_proto_init() }
func file_props_proto_init() {
	if File_props_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_props_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_props_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HProps); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_props_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SProps); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_props_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_props_proto_goTypes,
		DependencyIndexes: file_props_proto_depIdxs,
		MessageInfos:      file_props_proto_msgTypes,
	}.Build()
	File_props_proto = out.File
	file_props_proto_rawDesc = nil
	file_props_proto_goTypes = nil
	file_props_proto_depIdxs = nil
}
