apiVersion: batch/v1
kind: CronJob
metadata:
  name: notifier-cronjob
spec:
  # UTC
  schedule: "0 14 * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: notifier
            image: gcr.io/${_PROJECT_ID}/notifier:v0.0.1
            imagePullPolicy: IfNotPresent
          restartPolicy: Never