apiVersion: v1
kind: Service
metadata:
  name: registerer
spec:
  type: ClusterIP
  selector:
    app: registerer
  ports:
  - port: 50051
    targetPort: 50051
    name: grpc
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registerer
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: registerer
  template:
    metadata:
      labels:
        app: registerer
    spec:
      containers:
      - name: registerer
        image: gcr.io/${_PROJECT_ID}/registerer:v0.0.1
        imagePullPolicy: IfNotPresent