# on:
#   push:
#     branches:
#       - main

# name: Build and Deploy Containers
# env:
#   PROJECT_ID: ${{ secrets.PROJECT_ID }}
#   _PROJECT_ID: ${{ secrets.PROJECT_ID }}
#   REPO_NAME_NOTIFIER: notifier
#   REPO_NAME_REGISTERER: registerer
#   REPO_NAME_AGGREGATOR: aggregator
#   COMMIT_SHA: v0.0.1

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Set up for Cloud SDK
#         uses: google-github-actions/setup-gcloud@master
#         with:
#           project_id: ${{ env.PROJECT_ID }}
#           export_default_credentials: true
        
#       - name: Authorize Docker push
#         run: gcloud auth configure-docker
      
#       - name: Build and Deploy
#         run: make cbuild